### ISSUE TITLE
Cannot Run In Device

### ISSUE THREAD

**Issue by seirifat** [xendit/xendit-sdk-ios#1]
Why it can't be run in device?
If its running in emulator, it's run well. but when I debug the apps that using Xendit-sdk to device, and it's error

`'Xendit' is unavailable: cannot find Swift declaration for this class
`

Thanks,
Regards

**Comment by 0505gonzalez** [comment]
Hi @seirifat, our team is investigating this issue and will have a solution for you soon.

**Comment by seirifat** [comment]
Hi @0505gonzalez , thanks!
I'll waiting for update :)

Regards

**Comment by 0505gonzalez** [comment]
@seirifat We've addressed this issue in release 1.0.1. Please let me know if you run into any additional issues.

**Comment by seirifat** [comment]
Thanks a lot, @0505gonzalez 
yes of course, with my pleasure

Best Regards
