### ISSUE TITLE
dyld: Symbol not found: __swiftEmptyDictionaryStorage

### ISSUE THREAD

**Issue by indrajaumil** [xendit/xendit-sdk-ios#4]
Hi,

I got this message after build: 
_dyld: Symbol not found: __swiftEmptyDictionaryStorage_
Xendit ios sdk with cocoapods (Xendit 1.1.1)
Here is the full error message:
`dyld: Symbol not found: __swiftEmptyDictionaryStorage
  Referenced from: xyz/Library/Developer/CoreSimulator/Devices/3AFCD4C9-6EF4-4BD1-ABA3-62CEA1604F44/data/Containers/Bundle/Application/B776375D-24F4-41E1-B04A-6DCE4A2C83AF/RNXendit.app/Frameworks/Xendit.framework/Xendit
  Expected in: xyz/Library/Developer/CoreSimulator/Devices/3AFCD4C9-6EF4-4BD1-ABA3-62CEA1604F44/data/Containers/Bundle/Application/B776375D-24F4-41E1-B04A-6DCE4A2C83AF/RNXendit.app/Frameworks/libswiftCore.dylib
 in xyz/Library/Developer/CoreSimulator/Devices/3AFCD4C9-6EF4-4BD1-ABA3-62CEA1604F44/data/Containers/Bundle/Application/B776375D-24F4-41E1-B04A-6DCE4A2C83AF/RNXendit.app/Frameworks/Xendit.framework/Xendit`

Build tool: Xcode 8.2.1

Please help.

**Comment by 0505gonzalez** [comment]
Hi @khancute, 

If I understand correctly, you are having problems building an application with the xendit library. What OS are you targeting? 

Perhaps this might help https://stackoverflow.com/questions/6344560/dyld-symbol-not-found-error-how-to-resolve-this-issue

If not, have you taken a look at our example? https://github.com/xendit/xendit-sdk-ios/tree/master/XenditExample has  both Swift and Objective C examples.

**Comment by indrajaumil** [comment]
@0505gonzalez, we're build react native and trying to integrate xendit library in it.
When trying to use provided example, the build was failed with the following error message:
`/xendit-sdk-ios/XenditExample/XenditExample/Controllers/ViewController.swift:10:8: Module compiled with Swift 3.1 cannot be imported in Swift 3.0.2: /xendit-sdk-ios/XenditExample/../Xendit.framework/Modules/Xendit.swiftmodule/x86_64.swiftmodule`

Please advise.

**Comment by 0505gonzalez** [comment]
I see. The library was built using Swift 3.1. To get the example to work, you'd just need to build using  Swift 3.1, which should be backwards compatible with 3.0.2. I think updating your XCode to a slightly newer version should do it.

**Comment by indrajaumil** [comment]
@0505gonzalez i have updated my xcode, it currently have swift version 3.2 and 4.0, when i use swift 3.2, it still show the same kind of error although with different version of swift.
`
/xendit-sdk-ios/XenditExample/XenditExample/Controllers/ViewController.swift:10:8: Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /xendit-sdk-ios/XenditExample/../Xendit.framework/Modules/Xendit.swiftmodule/x86_64.swiftmodule
`

**Comment by 0505gonzalez** [comment]
Hi @khancute we just rebuild using 3.2. Try sdk version 1.1.2.

**Comment by indrajaumil** [comment]
Hi @0505gonzalez thanks for the update, it worked using version 1.1.2. Cheers
